/* automatically generated by rust-bindgen 0.72.1 */

// this was not auto-gen
#![allow(dead_code)]

pub const _SYS_USER_H: u32 = 1;
pub const PAGE_SHIFT: u32 = 12;
pub const PAGE_SIZE: u32 = 4096;
pub const PAGE_MASK: i32 = -4096;
pub const NBPG: u32 = 4096;
pub const UPAGES: u32 = 1;
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct user_fpregs_struct {
    pub cwd: ::std::os::raw::c_ushort,
    pub swd: ::std::os::raw::c_ushort,
    pub ftw: ::std::os::raw::c_ushort,
    pub fop: ::std::os::raw::c_ushort,
    pub rip: ::std::os::raw::c_ulonglong,
    pub rdp: ::std::os::raw::c_ulonglong,
    pub mxcsr: ::std::os::raw::c_uint,
    pub mxcr_mask: ::std::os::raw::c_uint,
    pub st_space: [::std::os::raw::c_uint; 32usize],
    pub xmm_space: [::std::os::raw::c_uint; 64usize],
    pub padding: [::std::os::raw::c_uint; 24usize],
}
#[repr(C)]
#[derive(Debug, Copy, Clone)]
pub struct user_regs_struct {
    pub r15: ::std::os::raw::c_ulonglong,
    pub r14: ::std::os::raw::c_ulonglong,
    pub r13: ::std::os::raw::c_ulonglong,
    pub r12: ::std::os::raw::c_ulonglong,
    pub rbp: ::std::os::raw::c_ulonglong,
    pub rbx: ::std::os::raw::c_ulonglong,
    pub r11: ::std::os::raw::c_ulonglong,
    pub r10: ::std::os::raw::c_ulonglong,
    pub r9: ::std::os::raw::c_ulonglong,
    pub r8: ::std::os::raw::c_ulonglong,
    pub rax: ::std::os::raw::c_ulonglong,
    pub rcx: ::std::os::raw::c_ulonglong,
    pub rdx: ::std::os::raw::c_ulonglong,
    pub rsi: ::std::os::raw::c_ulonglong,
    pub rdi: ::std::os::raw::c_ulonglong,
    pub orig_rax: ::std::os::raw::c_ulonglong,
    pub rip: ::std::os::raw::c_ulonglong,
    pub cs: ::std::os::raw::c_ulonglong,
    pub eflags: ::std::os::raw::c_ulonglong,
    pub rsp: ::std::os::raw::c_ulonglong,
    pub ss: ::std::os::raw::c_ulonglong,
    pub fs_base: ::std::os::raw::c_ulonglong,
    pub gs_base: ::std::os::raw::c_ulonglong,
    pub ds: ::std::os::raw::c_ulonglong,
    pub es: ::std::os::raw::c_ulonglong,
    pub fs: ::std::os::raw::c_ulonglong,
    pub gs: ::std::os::raw::c_ulonglong,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub struct user {
    pub regs: user_regs_struct,
    pub u_fpvalid: ::std::os::raw::c_int,
    pub i387: user_fpregs_struct,
    pub u_tsize: ::std::os::raw::c_ulonglong,
    pub u_dsize: ::std::os::raw::c_ulonglong,
    pub u_ssize: ::std::os::raw::c_ulonglong,
    pub start_code: ::std::os::raw::c_ulonglong,
    pub start_stack: ::std::os::raw::c_ulonglong,
    pub signal: ::std::os::raw::c_longlong,
    pub reserved: ::std::os::raw::c_int,
    pub __bindgen_anon_1: user__bindgen_ty_1,
    pub __bindgen_anon_2: user__bindgen_ty_2,
    pub magic: ::std::os::raw::c_ulonglong,
    pub u_comm: [::std::os::raw::c_char; 32usize],
    pub u_debugreg: [::std::os::raw::c_ulonglong; 8usize],
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union user__bindgen_ty_1 {
    pub u_ar0: *mut user_regs_struct,
    pub __u_ar0_word: ::std::os::raw::c_ulonglong,
}
#[repr(C)]
#[derive(Copy, Clone)]
pub union user__bindgen_ty_2 {
    pub u_fpstate: *mut user_fpregs_struct,
    pub __u_fpstate_word: ::std::os::raw::c_ulonglong,
}
